/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tiers: Tier;
    categories: Category;
    produits: Produit;
    emplacements: Emplacement;
    stocks: Stock;
    mouvements_stock: MouvementsStock;
    bons_de_livraison: BonsDeLivraison;
    factures_blf: FacturesBlf;
    historique_prix: HistoriquePrix;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tiers: TiersSelect<false> | TiersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    produits: ProduitsSelect<false> | ProduitsSelect<true>;
    emplacements: EmplacementsSelect<false> | EmplacementsSelect<true>;
    stocks: StocksSelect<false> | StocksSelect<true>;
    mouvements_stock: MouvementsStockSelect<false> | MouvementsStockSelect<true>;
    bons_de_livraison: BonsDeLivraisonSelect<false> | BonsDeLivraisonSelect<true>;
    factures_blf: FacturesBlfSelect<false> | FacturesBlfSelect<true>;
    historique_prix: HistoriquePrixSelect<false> | HistoriquePrixSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tiers".
 */
export interface Tier {
  id: number;
  type_tier: 'Client' | 'Fournisseur';
  raison_sociale: string;
  telephone?: string | null;
  adresse?: string | null;
  matricule_fiscal?: string | null;
  solde_actuel?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  nom_categorie: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produits".
 */
export interface Produit {
  id: number;
  nom_produit: string;
  nom_produit_ar?: string | null;
  nom_produit_derja?: string | null;
  categorie_id?: (number | null) | Category;
  prix_achat?: number | null;
  prix_vente_gros?: number | null;
  prix_vente_detail?: number | null;
  unite_mesure?: ('Kg' | 'Piece') | null;
  date_prix?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emplacements".
 */
export interface Emplacement {
  id: number;
  nom_emplacement: string;
  type_emplacement?: ('Depot' | 'Magasin') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stocks".
 */
export interface Stock {
  id: number;
  produit_id: number | Produit;
  emplacement_id: number | Emplacement;
  quantite_disponible: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mouvements_stock".
 */
export interface MouvementsStock {
  id: number;
  type_mouvement: 'Entree_Initiale' | 'Transfert';
  produit_id: number | Produit;
  emplacement_source_id?: (number | null) | Emplacement;
  emplacement_destination_id: number | Emplacement;
  quantite_mouvement: number;
  date_mouvement: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bons_de_livraison".
 */
export interface BonsDeLivraison {
  id: number;
  numero_bl: string;
  tier_id: number | Tier;
  /**
   * Emplacement d'où la marchandise est prélevée
   */
  source_emplacement?: ('Depot' | 'Magasin') | null;
  type_document: 'Achat' | 'Vente';
  statut?: ('Brouillon' | 'Livre' | 'Facture') | null;
  montant_total_bl?: number | null;
  date_creation?: string | null;
  lignes?:
    | {
        produit_id: number | Produit;
        quantite: number;
        prix_unitaire: number;
        sous_total?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factures_blf".
 */
export interface FacturesBlf {
  id: number;
  numero_blf: string;
  tier_id: number | Tier;
  statut_paiement?: ('Non_Paye' | 'Partiel' | 'Paye') | null;
  montant_total_facture?: number | null;
  date_facturation?: string | null;
  bls?: (number | BonsDeLivraison)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historique_prix".
 */
export interface HistoriquePrix {
  id: number;
  produit_id: number | Produit;
  prix_achat?: number | null;
  prix_vente_gros?: number | null;
  prix_vente_detail?: number | null;
  date_historique: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tiers';
        value: number | Tier;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'produits';
        value: number | Produit;
      } | null)
    | ({
        relationTo: 'emplacements';
        value: number | Emplacement;
      } | null)
    | ({
        relationTo: 'stocks';
        value: number | Stock;
      } | null)
    | ({
        relationTo: 'mouvements_stock';
        value: number | MouvementsStock;
      } | null)
    | ({
        relationTo: 'bons_de_livraison';
        value: number | BonsDeLivraison;
      } | null)
    | ({
        relationTo: 'factures_blf';
        value: number | FacturesBlf;
      } | null)
    | ({
        relationTo: 'historique_prix';
        value: number | HistoriquePrix;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tiers_select".
 */
export interface TiersSelect<T extends boolean = true> {
  type_tier?: T;
  raison_sociale?: T;
  telephone?: T;
  adresse?: T;
  matricule_fiscal?: T;
  solde_actuel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nom_categorie?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produits_select".
 */
export interface ProduitsSelect<T extends boolean = true> {
  nom_produit?: T;
  nom_produit_ar?: T;
  nom_produit_derja?: T;
  categorie_id?: T;
  prix_achat?: T;
  prix_vente_gros?: T;
  prix_vente_detail?: T;
  unite_mesure?: T;
  date_prix?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emplacements_select".
 */
export interface EmplacementsSelect<T extends boolean = true> {
  nom_emplacement?: T;
  type_emplacement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stocks_select".
 */
export interface StocksSelect<T extends boolean = true> {
  produit_id?: T;
  emplacement_id?: T;
  quantite_disponible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mouvements_stock_select".
 */
export interface MouvementsStockSelect<T extends boolean = true> {
  type_mouvement?: T;
  produit_id?: T;
  emplacement_source_id?: T;
  emplacement_destination_id?: T;
  quantite_mouvement?: T;
  date_mouvement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bons_de_livraison_select".
 */
export interface BonsDeLivraisonSelect<T extends boolean = true> {
  numero_bl?: T;
  tier_id?: T;
  source_emplacement?: T;
  type_document?: T;
  statut?: T;
  montant_total_bl?: T;
  date_creation?: T;
  lignes?:
    | T
    | {
        produit_id?: T;
        quantite?: T;
        prix_unitaire?: T;
        sous_total?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factures_blf_select".
 */
export interface FacturesBlfSelect<T extends boolean = true> {
  numero_blf?: T;
  tier_id?: T;
  statut_paiement?: T;
  montant_total_facture?: T;
  date_facturation?: T;
  bls?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historique_prix_select".
 */
export interface HistoriquePrixSelect<T extends boolean = true> {
  produit_id?: T;
  prix_achat?: T;
  prix_vente_gros?: T;
  prix_vente_detail?: T;
  date_historique?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}